[package]
name = "day10"
version = "0.1.0"
authors = ["Stephan Pernkopf <stephan@pernkopf.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
